from flask import Flask,jsonify,redirect # import flask and jsonify
import os #import os to use the dot env key
from src.auth import auth
from src.bookmarks import bookmarks
from src.database import database,Bookmark
from flask_jwt_extended import JWTManager


def create_app(test_config =None):
    app=Flask(__name__,instance_relative_config=True)

    if test_config is None:
        app.config.from_mapping(
            SECRET_KEY=os.environ.get("SECRET_KEY"),#obtain the secret key from the .env file
            SQLALCHEMY_DATABASE_URI=os.environ.get("SQLALCHEMY_DATABASE_URI"),#obtain the database URI from the flask env
            SQLALCHEMY_TRACK_MODIFICATIONS=False, #  suppress the modifiation error generated by the Sql Alchemy.
            JWT_SECRET_KEY=os.environ.get('JWT_SECRET_KEY')
        )
    else:
        app.config.from_mapping(test_config)
    database.app=app
    database.init_app(app) # control the integration of a pacckage to one or more Flask application
    JWTManager(app)#configure jwt so that when we call it can be known it's already there
    app.register_blueprint(auth) # register auth blueprint
    app.register_blueprint(bookmarks) #register bookmarks blueprint

 #redirect a page after being given a short url to the url       
    @app.get("/<short_url>")
    def redirect_to_url(short_url):
        try:
            single_bookmark = Bookmark.query.filter_by(short_url=short_url).first_or_404() #get the single bookmark using the url given
            if single_bookmark: # if it exist
                single_bookmark.visits=single_bookmark.visit+1 #then add visits to +1
                database.session.commit() #save it to the database
                return redirect(single_bookmark.url) # return a redirect to the url for the single_bookmark
            
        except:
            return jsonify({
                "message":"An error occcured"
            })
        
        
        
    return app